default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  # host: localhost

development:
  <<: *default
  database: book_database_development

test:
  <<: *default
  database: book_database_test

production:
  <<: *default
  database: book_database_production
  # username: yukosugiyama
  # password:
